# Generated by Django 6.0 on 2025-12-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='originals/')),
                ('result', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
